---
- name: Demo Playbook
  hosts: 10.55.4.211
  gather_facts: false

  tasks:
    - name: Hello World
      ansible.builtin.debug:
        msg: "Hello from GitHub!"

    - name: List all systemd services
      ansible.builtin.command: systemctl list-units --type=service --all
      register: systemctl_services
      changed_when: false

    - name: Display systemd services
      ansible.builtin.debug:
        var: systemctl_services.stdout_lines

    - name: Check SSH service status
      ansible.builtin.command: systemctl status sshd
      register: ssh_status
      changed_when: false

    - name: Display SSH service status
      ansible.builtin.debug:
        var: ssh_status.stdout_lines

    - name: Get SSH service active timestamp
      ansible.builtin.command: systemctl show sshd --property=ActiveEnterTimestamp
      register: ssh_timestamp
      changed_when: false

    - name: Display SSH service start timestamp
      ansible.builtin.debug:
        msg: "{{ ssh_timestamp.stdout }}"
